/**
 * Node HTTP server adapter for Stax apps.
 *
 * Deploy target: a long-lived Node process serving HTTP requests. The
 * adapter synthesizes a `dist/server/index.js` that boots
 * `NodeHttpServer`, listens on a configurable port, serves client assets
 * statically from `dist/client/`, and falls back to the user's app for
 * everything else.
 *
 * The user runs `pnpm serve` which is literally `node dist/server/index.js`.
 * No `tsx`, no runtime module loader. Everything is pre-built.
 *
 * ```ts
 * // vite.config.ts
 * import { defineConfig } from "vite";
 * import { staxPlatform, nodeAdapter } from "@stax-ui/vite-plugin";
 *
 * export default defineConfig({
 *   plugins: [
 *     staxPlatform({
 *       app: "src/app.ts",
 *       client: "src/client.ts",
 *       adapter: nodeAdapter({ port: 3000 }),
 *     }),
 *   ],
 * });
 * ```
 */

import type { StaxAdapter } from "./adapter.js";

export type { SsrEntryContext, StaxAdapter } from "./adapter.js";

export interface NodeAdapterOptions {
  /**
   * Port the production server listens on. Overridable at runtime via
   * `PORT` env var — the generated entry reads `process.env.PORT` first,
   * falls back to this value, then to `3000`.
   */
  readonly port?: number;

  /**
   * URL of the client script injected into the SSR'd document. Resolved
   * at build time to the hashed filename if Vite emits one; defaults to
   * `"/client.js"` matching the convention `vite build` produces for the
   * `client` entry.
   */
  readonly clientScript?: string;

  /**
   * URLs for stylesheets injected into the SSR'd document. Defaults to
   * `["/styles.css"]`. Pass `[]` if your app has no top-level stylesheet
   * (e.g. all styles are inlined via a framework like Tailwind in JIT mode).
   */
  readonly styles?: readonly string[];
}

export const nodeAdapter = (options: NodeAdapterOptions = {}): StaxAdapter => {
  const port = options.port ?? 3000;
  const clientScript = options.clientScript ?? "/client.js";
  const styles = options.styles ?? ["/styles.css"];

  return {
    name: "node",
    clientBuildOptions: {
      // Stable name because the generated server bundle hard-codes
      // `/client.js` in `document.scripts` and in its static-file serving
      // path. The Node server doesn't read a manifest at runtime.
      outDir: "dist/client",
      entryFileNames: "client.js",
    },
    ssrEntryModule: (ctx) => {
      const appImport = JSON.stringify(ctx.appModuleId);
      const scriptsLit = JSON.stringify([clientScript, ...ctx.scripts]);
      const stylesLit = JSON.stringify([...styles, ...ctx.styles]);
      const clientDirLit = JSON.stringify(ctx.clientRelativeDir);
      return `// Generated by @stax-ui/platform/node-adapter.
// Do not edit — regenerated on every \`vite build\`.

import { createServer } from "node:http";
import * as path from "node:path";
import { HttpServer } from "@effect/platform";
import { NodeHttpServer, NodeRuntime } from "@effect/platform-node";
import { Effect, Layer } from "effect";

import * as userApp from ${appImport};
import { serveStatic } from "@stax-ui/platform/node-adapter/runtime";

const port = Number(process.env.PORT) || ${port};
const here = path.dirname(new URL(import.meta.url).pathname);
const clientDir = path.resolve(here, ${clientDirLit});

const app = userApp.makeApp({
  scripts: ${scriptsLit},
  styles: ${stylesLit},
});

// Try to serve a static asset first; fall back to the Stax app.
const handler = serveStatic(clientDir).pipe(Effect.orElse(() => app));

let ServerLive = HttpServer.serve(handler).pipe(
  Layer.provide(NodeHttpServer.layer(createServer, { port })),
);

// Users can export an \`AppLayer\` from their app module to provide
// services (DB, auth, config) at server scope. Bracket access so
// Rollup / Vite don't warn when the export is omitted (optional).
const appLayer = userApp["AppLayer"];
if (appLayer) {
  ServerLive = Layer.provide(ServerLive, appLayer);
}

console.log(\`Server running at http://localhost:\${port}\`);
NodeRuntime.runMain(Layer.launch(ServerLive));
`;
    },
  };
};
