/**
 * SSG (static site generation) adapter for Stax apps.
 *
 * Deploy target: pre-rendered HTML files served from any static file
 * host (Vercel, Cloudflare Pages, Netlify, GitHub Pages, S3, Nginx).
 * No runtime server.
 *
 * The adapter synthesizes a build-time `dist/server/index.js` that
 * imports the user's `makeApp` + `router`, fires synthetic GET requests
 * at every `Route.static` route, and writes each response body as an
 * `index.html` under the matching path in `dist/`. Also writes a
 * `dist/404.html` from the router's fallback if one is defined.
 *
 * ```ts
 * // vite.config.ts
 * import { defineConfig } from "vite";
 * import { ssgAdapter, staxPlatform } from "@stax-ui/vite-plugin";
 *
 * export default defineConfig({
 *   plugins: [
 *     staxPlatform({
 *       app: "src/main.ts",
 *       client: "src/client.ts",
 *       adapter: ssgAdapter(),
 *     }),
 *   ],
 * });
 * ```
 *
 * The user's `src/main.ts` keeps the same shape as the SSR template —
 * exports `makeApp(opts)` and optional `AppLayer` — but must ALSO
 * re-export `router` from its `./routes.js` module so the SSG adapter
 * can enumerate static routes:
 *
 * ```ts
 * export { router } from "./routes.js";
 * export const makeApp = (opts) => ...;
 * export const AppLayer = undefined;
 * ```
 */

import type { StaxAdapter } from "./adapter.js";

export type { AppOptions, SsrEntryContext, StaxAdapter } from "./adapter.js";

export interface SsgAdapterOptions {
  /**
   * Directory the generated HTML files should land in, relative to the
   * project root. Defaults to `"dist"` — HTML lives next to client
   * assets so a static file server can serve the whole tree from one
   * root.
   */
  readonly outDir?: string;

  /**
   * URL(s) of the hashed client script injected into the SSG'd document.
   * Defaults to `"/client.js"`. Normally overridden by reading the Vite
   * client build's `.vite/manifest.json` at build time, but the adapter
   * accepts a static override if your client-side setup is unusual.
   */
  readonly clientScript?: string;

  /**
   * URL(s) of the hashed stylesheets. Defaults to `"/styles.css"`.
   * Same manifest-override rules as `clientScript`.
   */
  readonly styles?: readonly string[];
}

export const ssgAdapter = (options: SsgAdapterOptions = {}): StaxAdapter => {
  const outDir = options.outDir ?? "dist";
  const clientScript = options.clientScript ?? "/client.js";
  const styles = options.styles ?? ["/styles.css"];

  return {
    name: "ssg",
    clientBuildOptions: {
      // SSG serves HTML + assets from the same root. Hashed asset
      // filenames + a Vite manifest let the SSG runtime discover the
      // real URLs at build time and bake them into the generated HTML.
      outDir,
      manifest: true,
    },
    afterSsrBuild: async (ctx) => {
      // The generated entry's top-level `await runSsgBuild(...)` does
      // the actual work. Dynamic-import it so Node ESM executes it.
      await import(/* @vite-ignore */ ctx.ssrEntryPath);
    },
    ssrEntryModule: (ctx) => {
      const appImport = JSON.stringify(ctx.appModuleId);
      const scriptsLit = JSON.stringify([clientScript, ...ctx.scripts]);
      const stylesLit = JSON.stringify([...styles, ...ctx.styles]);
      const outDirLit = JSON.stringify(outDir);
      const clientRelLit = JSON.stringify(ctx.clientRelativeDir);
      return `// Generated by @stax-ui/platform/ssg-adapter.
// Do not edit — regenerated on every \`vite build\`.

import * as userApp from ${appImport};
import { runSsgBuild } from "@stax-ui/platform/ssg-adapter/runtime";

const appLayer = userApp["AppLayer"];

await runSsgBuild({
  makeApp: userApp.makeApp,
  router: userApp.router,
  appLayer,
  outDir: ${outDirLit},
  scripts: ${scriptsLit},
  styles: ${stylesLit},
  // Where the adapter can find the client build's manifest for
  // extracting hashed script/style URLs. Relative to this entry.
  clientManifestRelativeDir: ${clientRelLit},
});
`;
    },
  };
};
